platform :ios, '16.0'

target 'MatzipBook' do
  use_frameworks!
  
  # Pods for MatzipBook
  pod 'SwiftLint'
  pod 'SnapKit'
  pod 'Then'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end
  end
end
